/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arbolapp;

import com.mycompany.arbolapp.ventana2;

/**
 *
 * @author erick
 */
public class ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    public ventana1() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAVISO = new javax.swing.JTextField();
        jButtonCargar = new javax.swing.JButton();
        jTextFieldARCHIVO = new javax.swing.JTextField();
        jButtonTARGARYEN = new javax.swing.JButton();
        jButtonBARATHEON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaJSON = new javax.swing.JTextArea();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldAVISO.setEditable(false);
        jTextFieldAVISO.setBackground(new java.awt.Color(253, 0, 0));
        jTextFieldAVISO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldAVISO.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldAVISO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAVISO.setText("IMPORTANTE : Este programa solo lee archivos de tipo .json");
        jTextFieldAVISO.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldAVISO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAVISOActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAVISO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        jButtonCargar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCargar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCargar.setText("Cargar");
        jButtonCargar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButtonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, -1));
        getContentPane().add(jTextFieldARCHIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 310, 30));

        jButtonTARGARYEN.setBackground(new java.awt.Color(204, 204, 204));
        jButtonTARGARYEN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTARGARYEN.setText("Targaryen");
        jButtonTARGARYEN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButtonTARGARYEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 30));

        jButtonBARATHEON.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBARATHEON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBARATHEON.setText("Baratheon");
        jButtonBARATHEON.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButtonBARATHEON, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, 30));

        jTextAreaJSON.setEditable(false);
        jTextAreaJSON.setColumns(20);
        jTextAreaJSON.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextAreaJSON.setRows(5);
        jScrollPane1.setViewportView(jTextAreaJSON);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 610, 330));

        jButtonSiguiente.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(201, 64, 231));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Arbol Genealogico");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 770, -1));

        jLabelFONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HD-wallpaper-throne-game-of-thrones-got-thrones.jpg"))); // NOI18N
        getContentPane().add(jLabelFONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
      ventana2 v2 = new ventana2();
      v2.setV1(this);
      v2.setVisible(true);
      this.setVisible(false);
      
      
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldAVISOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAVISOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAVISOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBARATHEON;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonTARGARYEN;
    private javax.swing.JLabel jLabelFONDO;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaJSON;
    private javax.swing.JTextField jTextFieldARCHIVO;
    private javax.swing.JTextField jTextFieldAVISO;
    // End of variables declaration//GEN-END:variables
}
