/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arbolapp;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.graphstream.graph.Graph;
import org.graphstream.stream.SinkAdapter;
import org.graphstream.ui.swingViewer.ViewPanel;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.view.ViewerListener;
import org.graphstream.ui.view.ViewerPipe;

/**
 *
 * @author Godoy
 */
public class VentanaInicio extends javax.swing.JFrame {
        private GestorGenealogico gestorGenealogico;

        
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelPrecargadas = new javax.swing.JPanel();
        jButtonBaratheon = new javax.swing.JButton();
        jButtonTargaryen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanelBuscador = new javax.swing.JPanel();
        Buscadores = new javax.swing.JLabel();
        BuscarNombre = new javax.swing.JButton();
        BuscarTitulo = new javax.swing.JButton();
        BuscarGeneracion = new javax.swing.JButton();
        PanelJSON = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        AreaJson = new javax.swing.JTextField();
        PanelRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacionRegistro = new javax.swing.JTextArea();
        jPanelArbol = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 480));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrecargadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelPrecargadas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBaratheon.setText("Baratheon");
        jButtonBaratheon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaratheonActionPerformed(evt);
            }
        });
        PanelPrecargadas.add(jButtonBaratheon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        jButtonTargaryen.setText("Targaryen");
        jButtonTargaryen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTargaryenActionPerformed(evt);
            }
        });
        PanelPrecargadas.add(jButtonTargaryen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cargar");
        PanelPrecargadas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(PanelPrecargadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        PanelBuscador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelBuscador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Buscadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Buscadores.setText("Buscar Por:");
        PanelBuscador.add(Buscadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 16, 170, 30));

        BuscarNombre.setText("Nombre");
        BuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNombreActionPerformed(evt);
            }
        });
        PanelBuscador.add(BuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        BuscarTitulo.setText("Titulo");
        BuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTituloActionPerformed(evt);
            }
        });
        PanelBuscador.add(BuscarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        BuscarGeneracion.setText("Generacion");
        BuscarGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarGeneracionActionPerformed(evt);
            }
        });
        PanelBuscador.add(BuscarGeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 30));

        jPanel1.add(PanelBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 320));

        PanelJSON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelJSON.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSeleccionar.setText("Buscar JSON");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        PanelJSON.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, -1));

        AreaJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaJsonActionPerformed(evt);
            }
        });
        PanelJSON.add(AreaJson, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 490, 20));

        jPanel1.add(PanelJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 700, 50));

        PanelRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informacion de Registro:");
        PanelRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 30, 210, -1));

        informacionRegistro.setColumns(20);
        informacionRegistro.setLineWrap(true);
        informacionRegistro.setWrapStyleWord(true);
        informacionRegistro.setRows(5);
        jScrollPane1.setViewportView(informacionRegistro);

        PanelRegistro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 51, 170, 380));

        jPanel1.add(PanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 210, 450));

        jPanelArbol.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanelArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 480, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        // Configurar filtro para archivos JSON
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON (*.json)", "json");
        fileChooser.setFileFilter(filtro);
        fileChooser.setAcceptAllFileFilterUsed(false);
        // Mostrar el diálogo de selección de archivo
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File archivoSeleccionado = fileChooser.getSelectedFile();

            // Mostrar información del archivo seleccionado
            JOptionPane.showMessageDialog(this,
                    "Archivo seleccionado: " + archivoSeleccionado.getAbsolutePath(),
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            AreaJson.setText(archivoSeleccionado.getName());
            try {
            gestorGenealogico = new GestorGenealogico(archivoSeleccionado.getAbsolutePath());
            cargarGrafo();
        } catch (IOException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        } else {
            // Si el usuario cancela la selección
            JOptionPane.showMessageDialog(this,
                    "Selección cancelada.",
                    "Información",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void AreaJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaJsonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaJsonActionPerformed

    private void cargarGrafo() {
        TablaHash tablaHash = new TablaHash();

        // Pintar el árbol
        Graph grafo = gestorGenealogico.getGrafo(gestorGenealogico.personaRaiz);
        Viewer viewer = new Viewer(grafo, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewer.enableAutoLayout(); // Habilitar auto-layout
        ViewPanel viewPanel = viewer.addDefaultView(false); // Crear ViewPanel

        // Asegurar que jPanelArbol tiene un tamaño válido
        if (jPanelArbol.getWidth() == 0 || jPanelArbol.getHeight() == 0) {
            System.err.println("jPanelArbol no tiene un tamaño válido.");
            return;
        }

        // Agregar el ViewPanel al jPanelArbol
        jPanelArbol.removeAll();
        jPanelArbol.add(viewPanel, BorderLayout.CENTER);
        jPanelArbol.revalidate();
        jPanelArbol.repaint();

        // Configurar el ViewerPipe para eventos
        ViewerPipe pipe = viewer.newViewerPipe();
        pipe.addSink(grafo);

        pipe.addViewerListener(new ViewerListener() {

            @Override
            public void buttonPushed(String id) {
                Persona persona = gestorGenealogico.buscar(id); // Acceso a tablaHash
                if (persona != null) {
                    informacionRegistro.setText(persona.toString());
                    System.out.println(persona.toString()); // Mostrar información completa
                } else {
                    informacionRegistro.setText("No se encontró información para: " + id);

                    System.out.println("No se encontró información para el nodo: " + id);
                }
            }

            @Override
            public void viewClosed(String string) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            @Override
            public void buttonReleased(String string) {

            }
        });

        // Configuración de un Timer para gestionar los eventos de ViewerPipe
//        new javax.swing.Timer(50, e -> pipe.pump()).start();
        // Procesar eventos en un hilo separado
        new Thread(() -> {
            while (true) {
                pipe.pump(); // Procesar eventos
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }).start();

        // Depuración
        System.out.println("jPanelArbol size: " + jPanelArbol.getWidth() + "x" + jPanelArbol.getHeight());
        System.out.println("Graph nodes: " + grafo.getNodeCount());
        System.out.println("Graph edges: " + grafo.getEdgeCount());

    }

    private void jButtonTargaryenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTargaryenActionPerformed
        
       try {
            gestorGenealogico = new GestorGenealogico("Targaryen.json");
            cargarGrafo();
        } catch (IOException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonTargaryenActionPerformed

    private void jButtonBaratheonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaratheonActionPerformed
        try {
            gestorGenealogico = new GestorGenealogico("Baratheon.json");
            cargarGrafo();
        } catch (IOException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBaratheonActionPerformed

    private void BuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNombreActionPerformed
        BusquedaPorNombre VentanaNombre = new BusquedaPorNombre(gestorGenealogico);
        VentanaNombre.setvPrincipal(this);
        this.setVisible(false);
        VentanaNombre.setVisible(true);
    }//GEN-LAST:event_BuscarNombreActionPerformed

    private void BuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTituloActionPerformed
        BusquedaPorTitulo VentanaTitulo = new BusquedaPorTitulo();
        VentanaTitulo.setvPrincipal(this);
        this.setVisible(false);
        VentanaTitulo.setVisible(true);
    }//GEN-LAST:event_BuscarTituloActionPerformed

    private void BuscarGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarGeneracionActionPerformed
        BusquedaPorGeneracion VentanaGen = new BusquedaPorGeneracion();
        VentanaGen.setvPrincipal(this);
        this.setVisible(false);
        VentanaGen.setVisible(true);
    }//GEN-LAST:event_BuscarGeneracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaJson;
    private javax.swing.JLabel Buscadores;
    private javax.swing.JButton BuscarGeneracion;
    private javax.swing.JButton BuscarNombre;
    private javax.swing.JButton BuscarTitulo;
    private javax.swing.JPanel PanelBuscador;
    private javax.swing.JPanel PanelJSON;
    private javax.swing.JPanel PanelPrecargadas;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JTextArea informacionRegistro;
    private javax.swing.JButton jButtonBaratheon;
    private javax.swing.JButton jButtonTargaryen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelArbol;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
