/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2.Interfaz;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author erick
 */
public class Interfaz2 extends javax.swing.JFrame {
    private Interfaz1 p1;
    private JSONObject json;
    /**
     * Creates new form Interfaz2
     */
    public Interfaz2(JSONObject json) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.json = json;
    }

    private Interfaz2() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTNregresar = new javax.swing.JButton();
        BTNnombre = new javax.swing.JButton();
        BTNtitulo = new javax.swing.JButton();
        BTNgeneracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNregresar.setText("Regresar");
        BTNregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNregresarActionPerformed(evt);
            }
        });
        jPanel1.add(BTNregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BTNnombre.setText("Nombre");
        jPanel1.add(BTNnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 90, -1));

        BTNtitulo.setText("Título");
        jPanel1.add(BTNtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 90, -1));

        BTNgeneracion.setText("Generación");
        jPanel1.add(BTNgeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNregresarActionPerformed
        p1.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setVisible(false);       
    }//GEN-LAST:event_BTNregresarActionPerformed
    public void setP1(Interfaz1 p1){
        this.p1 = p1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNgeneracion;
    private javax.swing.JButton BTNnombre;
    private javax.swing.JButton BTNregresar;
    private javax.swing.JButton BTNtitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
